import { Urbanist, Geist_Mono } from 'next/font/google';
import './globals.css';

const fontPrimary = Urbanist({
  variable: '--font-primary',
  subsets: ['latin'],
});

// const fontSecondary = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${fontPrimary.variable} antialiased`}>{children}</body>
    </html>
  );
}
